### PR TITLE
 have setLogLevel set the global log level instead of the fancylogger log level

### PR DESCRIPTION
**Pull request by JensTimmerman**
This will show a lot of logging, also for all dependencies etc.

### CODE REVIEW

**Comment by JensTimmerman** [comment]
this still keeps fancylogger in it's namespace, but setLogLevel now sets the global loglevel for all new loggers.

**Comment by stdweird** [comment]
@JensTimmerman  this pr does soemthing very different then #246 
please close one of them

**Comment by JensTimmerman** [comment]
@stdweird which one?

**Comment by stdweird** [comment]
@JensTimmerman if i can replace the logging rootlogger with fancylogger, i'd say both. i gave it some more tought, this is not the way to proceed; and if you want to change the root logger loglevel, use `logging`. but lets wait for what i come up with.

**Pull request closed without merging**
