### PR TITLE
only include root logger name in non-debug mode

### PR DESCRIPTION
**Pull request by boegel**
`getRootLoggerName()` always returns "not available in optimized mode" when it is run under `python -O` (i.e., when `__debug__` is `False`), so it makes no sense to include it to construct the "full logger name"

### CODE REVIEW

**Comment by stdweird** [comment]
what does this change?

**Comment by stdweird** [comment]
sorry, didn't read the description :smile:

**Comment by stdweird** [comment]
test this please

**Comment by boegel** [comment]
In the case of EasyBuild (where `python -O` is used/`$PYTHONOPTIMIZE` is set), you get this as log messages:

```
== 2016-03-03 09:52:17,768 tools.robot INFO Using robot path(s): ['/Users/kehoste/work/easybuild-easyconfigs/easybuild/easyconfigs']
```

instead of this:

```
== 2016-03-03 09:52:17,768 not available in optimized mode.tools.robot INFO Using robot path(s): ['/Users/kehoste/work/easybuild-easyconfigs/easybuild/easyconfigs']
```

If `python -O` is not used, it doesn't change anything.

**Comment by boegel** [comment]
Please hold off merging this a little bit, since this breaks some nasty bit of code `eb`:

```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/kehoste/work/easybuild-framework/easybuild/main.py", line 47, in <module>
    from easybuild.tools.build_log import EasyBuildError, init_logging, print_msg, print_error, stop_logging
  File "easybuild/tools/build_log.py", line 182, in <module>
    del _init_fancylog.manager.loggerDict[_init_fancylog.name]
KeyError: 'root'
```

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
OK, this is not going to work, apparently the root logger name is key, even under `python -O` when it's "not available in debug mode"...

I'll figure out another way to get rid of the "not available in debug mode" in the EB logs.

**Comment by boegel** [comment]
superior solution in EB is to simply not include the logger name, but log location instead: https://github.com/hpcugent/easybuild-framework/pull/1649

**Pull request closed without merging**
