### PR TITLE
let Generaloption set global log level

### PR DESCRIPTION
**Pull request by JensTimmerman**

### CODE REVIEW

**Comment by stdweird** [comment]
i don't think this is the way to go. it's more useful that generaloption by default sets the root logger as a fancylogger. i'll make a PR soonish

**Comment by boegel** [comment]
@stdweird is it soonish yet?

We're still using `logging.info` and `logging.debug` in `irun, but without making sure that `logging` uses a `FancyLogger`, that's not really usable to get decent log messages...

**Comment by stdweird** [comment]
@boegel  is already merged https://github.com/hpcugent/vsc-base/pull/248

**Comment by stdweird** [comment]
@JensTimmerman are these PRs still required?

**Comment by boegel** [comment]
Ah, ok, I overlooked that because no new version was tagged, fixed that now, thanks @stdweird

**Pull request closed without merging**
