### PR TITLE
fix broken link to VSC website

### PR DESCRIPTION
**Pull request by boegel**
this must be a regex replace gone bad, https://vscentrum.be/nl/en most likely never worked...

### CODE REVIEW

**Comment by stdweird** [comment]
is this fixed in vsc-install?

**Comment by boegel** [comment]
not yet, but I can look into it

**Comment by boegel** [comment]
@stdweird https://github.com/hpcugent/vsc-install/pull/40

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Tests fail with

```
AttributeError: 'module' object has no attribute 'generaloption'
```

There's no way this change can have caused that...

**Comment by boegel** [comment]
@JensTimmerman any ideas?

**Comment by JensTimmerman** [comment]
yes, merge https://github.com/hpcugent/vsc-base/pull/227 first

**Comment by boegel** [comment]
fixed in #227

**Pull request closed without merging**
