### PR TITLE
added restclient example script

### PR DESCRIPTION
**Pull request by JensTimmerman**

### CODE REVIEW

**Comment by wdpypere** [comment]
HTTPError: HTTP Error 403: Forbidden

**Comment by boegel** [comment]
@wdpypere Needs a token?

**Comment by wdpypere** [comment]
No clue, just looking into this for "can we merge this or should it be closed" purposes.

**Comment by boegel** [comment]
@wdpypere Script works fine for me:

```
$ python github.py --year 2018
hpcugent.github.com
 -  itkovian 0
 -  JensTimmerman 0
 -  boegel 0
--TOTAL--
0

VSC-tools
 -  itkovian 0
--TOTAL--
0

testrepository
 -  JensTimmerman 0
--TOTAL--
0

vsc-ldap
 -  lpmi-13 1
 -  boegel 0
 -  piojo 0
 -  stdweird 0
 -  JensTimmerman 0
 -  itkovian 0
--TOTAL--
1

vsc-processcontrol
 -  boegel 0
 -  piojo 0
 -  itkovian 0
 -  JensTimmerman 0
 -  stdweird 0
--TOTAL--
0

vsc-mympirun
 -  wpoely86 0
 -  piojo 0
 -  itkovian 0
 -  JensTimmerman 0
 -  boegel 47
 -  stdweird 0
 -  Iepoev 0
 -  Caylo 0
--TOTAL--
47

vsc-mympirun-scoop
 -  piojo 0
 -  JensTimmerman 0
 -  boegel 0
 -  itkovian 0
 -  stdweird 0
--TOTAL--
0

vsc-base
 -  Silox 0
 -  Caylo 0
 -  riccardomurri 0
 -  piojo 0
 -  JensTimmerman 12
 -  itkovian 15
 -  boegel 9
 -  stdweird 0
--TOTAL--
36

vsc-passwords
 -  piojo 0
 -  JensTimmerman 0
--TOTAL--
0

vsc-filesystems
 -  JensTimmerman 0
 -  wdpypere 0
 -  wpoely86 0
 -  boegel 0
 -  piojo 0
 -  kwaegema 0
 -  stdweird 0
 -  itkovian 11
--TOTAL--
11

logstash-patterns
 -  kwaegema 0
 -  JensTimmerman 0
 -  alvarosimon 0
 -  stdweird 0
 -  itkovian 0
 -  piojo 0
 -  wpoely86 0
--TOTAL--
0

config-templates
 -  itkovian 0
 -  kwaegema 0
 -  alvarosimon 0
 -  piojo 0
 -  stdweird 0
--TOTAL--
0

master-scripts
 -  wdpypere 0
 -  stdweird 0
 -  piojo 0
 -  itkovian 0
--TOTAL--
0

jsonpickle
 -  itkovian 0
 -  pasku 0
 -  mvyskocil 0
 -  davidkhess 0
 -  alecthomas 0
 -  paulocheque 0
 -  meatballhat 0
 -  jaraco 0
 -  johnpaulett 0
 -  davvid 0
--TOTAL--
0

graphite-web
 -  Blackbaud-JesseHodges 0
 -  cobly 0
 -  jordanlewis 0
 -  bclermont 0
 -  jblaine 0
 -  kmike 0
 -  dcarley 0
 -  salerth 0
 -  amosshapira 0
 -  jwoschitz 0
 -  recursify 0
 -  whd 0
 -  pedronis 0
 -  ohlol 0
 -  gingerlime 0
 -  luxflux 0
 -  scobal 0
 -  ickymettle 0
 -  coredump 0
 -  jordansissel 0
 -  jerith 0
 -  dinomite 0
 -  magec 0
 -  statik 0
 -  bitprophet 0
 -  JoseCF 0
 -  octplane 0
 -  bmhatfield 0
 -  jdugan1024 0
 -  nleskiw 0
 -  Dieterbe 0
 -  obfuscurity 0
 -  carmelchas 0
 -  Silox 0
 -  tmm1 0
 -  mleinart 0
 -  cdavis 0
--TOTAL--
0

vsc_test_suite
 -  boegel 0
--TOTAL--
0

django-cas
 -  mcoconnor 0
 -  exogen 0
 -  greencm 0
--TOTAL--
0

aquilon-build-xmls
 -  piojo 0
--TOTAL--
0

easybuild-wiki
 -  ehiggs 0
 -  besserox 0
 -  wpoely86 0
 -  itkovian 0
 -  fgeorgatos 0
 -  JensTimmerman 0
 -  boegel 0
--TOTAL--
0

vsc-utils
 -  Silox 0
 -  boegel 0
 -  wdpypere 0
 -  wpoely86 0
 -  stdweird 0
 -  JensTimmerman 1
 -  itkovian 14
--TOTAL--
15

vsc-zk
 -  stdweird 0
 -  kwaegema 0
--TOTAL--
0

optcomplete-deps
 -  stdweird 0
 -  boegel 0
--TOTAL--
0

vsc_user_docs
 -  stdweird 0
 -  itkovian 0
 -  epauwels 0
 -  GeertBorstlap 0
 -  gjbex 0
 -  smoors 3
 -  alvarosimon 10
 -  mselwa 0
 -  wpoely86 0
 -  sbecuwe 6
 -  hajgato 0
 -  boegel 7
 -  JensTimmerman 0
 -  klust 0
 -  redfast00 325
--TOTAL--
351

hanythingondemand
 -  wpoely86 0
 -  ehiggs 0
 -  molden 0
 -  stdweird 0
 -  boegel 0
--TOTAL--
0

hust14_paper
 -  geimer 0
 -  boegel 0
--TOTAL--
0

csub
 -  JensTimmerman 0
 -  boegel 0
 -  wpoely86 0
--TOTAL--
0

environment-modules
 -  JensTimmerman 0
--TOTAL--
0

nested-dict
 -  itkovian 0
 -  bunbun 0
--TOTAL--
0

vsc-administration
 -  wdpypere 0
 -  piojo 0
 -  stdweird 7
 -  JensTimmerman 0
 -  itkovian 78
--TOTAL--
85

mympingpong
 -  JensTimmerman 0
 -  boegel 0
 -  wpoely86 0
 -  stdweird 0
 -  Iepoev 0
--TOTAL--
0
```

**Comment by boegel** [comment]
close/re-open to trigger tests...

**Comment by wdpypere** [comment]
@boegel tests fail

**Comment by boegel** [comment]
@wdpypere I know, and I don't have time to look into fixing this. Since this is just an example script, it's *really* low priority imho.

**Pull request closed without merging**
