### PR TITLE
fix formatting issues in README

### PR DESCRIPTION
**Pull request by boegel**
Fix formatting issues that prevent proper rendering on PyPI

Checks done using `readme-renderer` Python package, using `python setup.py check -rs`, cfr. https://gist.github.com/kennethreitz/8378ba05d1a50bea75da

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by stdweird** [comment]
Please don't merge this in until the test has been added to vsc-install

**Comment by JensTimmerman** [comment]
jenkins test this please

**Comment by JensTimmerman** [comment]
please rebase on master

**Comment by boegel** [comment]
blocked by https://github.com/hpcugent/vsc-install/pull/28

**Comment by JensTimmerman** [comment]
how will this ever work? that pr checks for valid rst code in the readme's, this is markdown?

**Comment by JensTimmerman** [comment]
jenkins test this please

@boegel please rebase this on master

**Comment by JensTimmerman** [comment]
I see, if you use the right subset of markdown and rst you get something that doesn't give errors. 
But it doesn't really look nice?

**Comment by boegel** [comment]
Seems like the rebase screwed up this PR pretty nicely...

This is supposed to be only about 2c21bb5d30e8b16003578bedb3cc872fa35d96f3, but since they actual fix would be to transform `README.md` into `README.rst`, which is required to make PyPI properly render things since it doesn't support MarkDown, I'll just go ahead and close this.

**Pull request closed without merging**
