### PR TITLE
Remove unused functions 'avail_subclasses_in' and 'modules_in_pkg_path'

### PR DESCRIPTION
**Pull request by ehiggs**
We couldn't find across our public and private githubs where these functions are used, so I'm offering this PR to remove them.

### CODE REVIEW

**Comment by stdweird** [comment]
test this please

**Comment by stdweird** [comment]
@ehiggs any other repos you can't trigger jenkins tests?

**Comment by ehiggs** [comment]
Probably most vsc projects that I haven't yet gotten my code deleting hands on. :)

**Comment by boegel** [comment]
Let me run the EB tests on top of this.

Also: missing version bump

**Comment by stdweird** [comment]
no version bump please. should be able to do clean as possible revert

**Comment by boegel** [comment]
Well, the removal is done in a single commit, so trivial to revert?

**Comment by boegel** [comment]
Anyway, a version bump in the next PR that gets merged is fine too.

**Comment by boegel** [comment]
Green light from EB framework test suite!

**Pull request merged**
