### PR TITLE
Adapt to vsc-install

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by stdweird** [comment]
Pr is meant to debug the issues in #217

**Comment by boegel** [comment]
@stdweird: wth is going on here?

Can you update the headers in a separate PR, it's obscuring things here.

**Comment by JensTimmerman** [comment]
@boegel this is what he is doing here

**Comment by ehiggs** [comment]
>@boegel this is what he is doing here

@boegel's point, then, is that the PR title should be "Updating headers for the new year".

**Comment by stdweird** [comment]
@ehiggs it's more than just the headers

**Pull request closed without merging**
