### PR TITLE
drop py27, py37 and py38, add py3.10 in github actions

### PR DESCRIPTION
**Pull request by wpoely86**

### CODE REVIEW

**Comment by wpoely86** [comment]
python 3.11 doesn't like the fancylogger tests. I'm not sure why it fails.

**Comment by boegel** [comment]
@wpoely86 Any reason why you want to drop testing with 3.7 and 3.8?

**Comment by wpoely86** [comment]
Why would we test those versions? 3.6 is RHEL8, 3.9 is RHEL9 and future.

**Comment by wdpypere** [comment]
@wpoely86 did you try 3.10? looking at the changelog for 3.11 I can't immediately find what causes this (although a lot of work around async stuff was done)

**Comment by wpoely86** [comment]
Yes, see https://github.com/hpcugent/vsc-base/actions/runs/3573457420/jobs/6007542646

python 3.10 works. I also couldn't find any change that explains it.

**Comment by wdpypere** [comment]
I'll fix in #337

**Pull request closed without merging**
